name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  # lottie: ^2.6.0
  flutter_svg: ^2.0.7
  # shared_preferences: ^2.2.0
  provider: ^6.0.5
  flutter_animate: ^4.2.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  lottie: ^2.7.0
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.1.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  # flutter_native_timezone: ^2.0.0 
  intl: ^0.18.1
  
  just_audio: ^0.9.22  # Make sure to use the latest version
  audioplayers: ^6.4.0
  flutter_staggered_animations: ^1.1.1
  # provider: ^6.0.5
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.8

  # meditation
  readmore: ^3.0.0
  dotted_dashed_line: ^0.0.3
  video_player: ^2.9.5
  chewie: ^1.11.3
  aws_s3_api: ^2.0.0
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/
    - assets/svg/
    - assets/images/meditation/focus/items/
    - assets/images/meditation/focus/video_thumbnails/
    - assets/images/meditation/relax/items/
    - assets/images/meditation/relax/video_thumbnails/
    - assets/images/meditation/mind/items/
    - assets/images/meditation/mind/video_thumbnails/
  #   - images/a_dot_ham.jpeg

  # For custom fonts, make sure the font files exist before adding.

  # fonts:
  # - family: Poppins
  #   fonts:
  #     - asset: assets/fonts/Poppins-Regular.ttf
  #     - asset: assets/fonts/Poppins-Bold.ttf
  #       weight: 700
  #     - asset: assets/fonts/Poppins-SemiBold.ttf
  #       weight: 600
